/**
 * Generates the build report the portfolio case study renders.
 *
 * The case study used to describe its own quality checks in hand-written
 * prose. That prose drifted: it claimed oxlint ran in the build when it does
 * not, and it never mentioned the accessibility or asset-weight gates because
 * those were added later. A claim you type once goes stale the moment the
 * build changes.
 *
 * So the page reads this file instead. It is derived from the real build
 * chain and the real gate thresholds, and it is regenerated on every build,
 * which means it cannot describe a check that is not actually wired up.
 *
 * Runs before `vite build` so the result can be imported directly rather than
 * fetched. Gates that need `dist/` are described from their configuration
 * rather than executed here.
 */

import { execFileSync } from "node:child_process"
import { readFile, writeFile, readdir, stat } from "node:fs/promises"
import { join } from "node:path"

const run = (script) => {
  try {
    return execFileSync("node", [script], { encoding: "utf8" })
  } catch (error) {
    // A failing gate is the build's problem, not the report's. Surface it and
    // stop, rather than quietly publishing a report that omits the failure.
    process.stderr.write(error.stdout ?? "")
    process.stderr.write(error.stderr ?? "")
    throw new Error(`${script} failed while generating the build report.`)
  }
}

const number = (source, pattern) => {
  const match = source.match(pattern)
  return match ? Number(match[1]) : null
}

const pkg = JSON.parse(await readFile("package.json", "utf8"))

// The chain is the source of truth for which gates actually run.
const chain = pkg.scripts.build
  .split("&&")
  .map((step) => step.trim())
  .map((step) => step.replace(/^node scripts\//, "").replace(/\.mjs$/, ""))

const a11yOut = run("scripts/check-a11y.mjs")
const weightOut = run("scripts/check-weight.mjs")

const a11ySource = await readFile("scripts/check-a11y.mjs", "utf8")
const glassSource = await readFile("scripts/check-glass.mjs", "utf8")
const weightSource = await readFile("scripts/check-weight.mjs", "utf8")

const walk = async (dir) => {
  const out = []
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) out.push(...(await walk(full)))
    else out.push(full)
  }
  return out
}

const imageFiles = (await Promise.all(["public/assets/images", "public/assets/journal"].map(walk))).flat()
const byFormat = {}
let imageBytes = 0
for (const file of imageFiles) {
  const ext = file.split(".").pop().toLowerCase()
  byFormat[ext] = (byFormat[ext] ?? 0) + 1
  imageBytes += (await stat(file)).size
}

const journalCount = (await readdir("src/data/journal/articles")).filter((f) => f.endsWith(".ts")).length

const glassRuleCount = (glassSource.match(/requiredSnippets = \[([\s\S]*?)\]/)?.[1] ?? "").split(",").filter((entry) => entry.includes('"')).length

const report = {
  generatedAt: new Date().toISOString().slice(0, 10),
  chain,
  gates: [    {
      id: "check-glass",
      label: "Glass surfaces",
      summary: `Confirms every layered-glass rule survived the CSS build, so the depth treatment cannot be silently dropped by a refactor or an over-eager purge.`,
      metric: `${glassRuleCount} rules verified`,
    },
    {
      id: "check-a11y",
      label: "Colour and target size",
      summary: `Recomputes contrast for every colour token pair in both themes against WCAG AA, and requires interactive text controls to be at least ${
        number(a11ySource, /TARGET_MIN_PX = (\d+)/) ?? 24
      }px tall. It caught four real contrast defects when it was introduced.`,
      metric: `${number(a11yOut, /passed \((\d+) checks\)/) ?? 0} checks`,
    },
    {
      id: "check-weight",
      label: "Asset weight",
      summary: `Fails on any image over ${
        number(weightSource, /MAX_IMAGE_KB = (\d+)/) ?? 400
      }KB, any unconverted raster, and any source model left where it would be deployed. Added after the homepage was found shipping 8MB.`,
      metric: `${(imageBytes / 1048576).toFixed(1)}MB of ${number(weightSource, /MAX_IMAGES_TOTAL_MB = (\d+)/) ?? 15}MB budget`,
    },
  ]
    // The chain is the source of truth. A gate that is no longer wired into the
    // build must disappear from the page, otherwise this section would advertise
    // a check that does not run, which is the exact drift it exists to prevent.
    .filter((gate) => chain.includes(gate.id)),
  assets: {
    imageCount: imageFiles.length,
    imageMb: Number((imageBytes / 1048576).toFixed(1)),
    formats: byFormat,
  },
  journalCount,
}

const banner = `// Generated by scripts/build-report.mjs on every build. Do not edit by hand.\n// Editing this file is pointless: the next build overwrites it.\n\n`

const body = `export type BuildGate = {
  id: string
  label: string
  summary: string
  metric: string
}

export type BuildReport = {
  generatedAt: string
  chain: string[]
  gates: BuildGate[]
  assets: { imageCount: number; imageMb: number; formats: Record<string, number> }
  journalCount: number
}

export const BUILD_REPORT: BuildReport = ${JSON.stringify(report, null, 2)}
`

// The opposite failure mode: a gate wired into the build that nobody wrote a
// description for would silently never reach the page. Fail loudly instead, so
// adding a gate forces you to explain it.
const undescribed = chain.filter((step) => step.startsWith("check-") && !report.gates.some((g) => g.id === step))
if (undescribed.length > 0) {
  console.error(
    `build-report: ${undescribed.join(", ")} run${undescribed.length === 1 ? "s" : ""} in the build but ` +
      `${undescribed.length === 1 ? "has" : "have"} no description in scripts/build-report.mjs. ` +
      `Add one so the case study describes what actually runs.`,
  )
  process.exit(1)
}

await writeFile("src/data/build-report.ts", banner + body)

console.log(
  `Build report: ${report.gates.length} gates, ${report.gates.map((g) => g.metric).join(", ")}.`
)
