/**
 * Social card generator.
 *
 * Every route gets its own 1200x630 card instead of all 36 sharing one image.
 * Cards are drawn in real Chrome from the site's own tokens, then committed, so
 * a normal `npm run build` needs no browser. Run this after adding an article:
 *
 *   npm run og
 *
 * check-og.mjs fails the build if a route is missing its card, so forgetting is
 * caught rather than shipped.
 */

import { mkdir, readdir, readFile, unlink, writeFile } from "node:fs/promises"
import { createHash } from "node:crypto"
import { existsSync } from "node:fs"
import { join } from "node:path"
import { cardSpecs, CARD_DIR, MANIFEST } from "./lib/og.mjs"
import { renderCard } from "./lib/og-template.mjs"

const OUT = new URL("../public/assets/og/", import.meta.url).pathname
const QUALITY = 88

// Cards are drawn at 2x. Platforms re-encode what they fetch, and handing them
// a 1200px JPEG to re-compress produced a visibly soft preview; giving them
// twice the pixels means their downscale is the last lossy step, not the second.
const SCALE = 2

const CHROME_PATHS = [
  "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
  "/Applications/Chromium.app/Contents/MacOS/Chromium",
  "/usr/bin/google-chrome",
  "/usr/bin/chromium",
  "/usr/bin/chromium-browser",
]

let chromium
try {
  ;({ chromium } = await import("playwright-core"))
} catch {
  console.error(
    "og-cards needs playwright-core to drive Chrome.\n" +
      "  npm i -D playwright-core\n" +
      "Cards are committed, so this is only needed when regenerating them."
  )
  process.exit(1)
}

const executablePath = CHROME_PATHS.find((path) => existsSync(path))
if (!executablePath) {
  console.error(`No Chrome or Chromium found. Looked in:\n${CHROME_PATHS.map((p) => `  ${p}`).join("\n")}`)
  process.exit(1)
}

const specs = await cardSpecs()
await mkdir(OUT, { recursive: true })

const browser = await chromium.launch({ executablePath })
const page = await browser.newPage({
  viewport: { width: 1200, height: 630 },
  deviceScaleFactor: SCALE,
})

const failures = []
const written = new Set()
const manifest = {}

/**
 * The hash goes in the filename so that an edited card is a new URL. Social
 * platforms cache the copy they derive from an image URL and do not re-derive
 * it when the bytes behind that URL change, so a card with a stable name can
 * never be corrected once it has been shared.
 *
 * It hashes the card's inputs rather than its output. Chrome's JPEG encoding is
 * not byte-reproducible — two identical runs differ on about two thirds of the
 * cards — so hashing the bytes would rename every card on every run and bust
 * every cached preview for no reason. The spec plus the template source is what
 * actually determines the design, and both are deterministic.
 */
const templateSource = await readFile(new URL("./lib/og-template.mjs", import.meta.url), "utf8")
function cardHash(spec) {
  return createHash("sha256")
    .update(templateSource)
    .update(`${SCALE}:${QUALITY}`)
    .update(JSON.stringify(spec))
    .digest("hex")
    .slice(0, 8)
}

for (const spec of specs) {
  const html = renderCard(spec)
  await page.setContent(html, { waitUntil: "load" })
  await page.waitForTimeout(180)

  // A clipped card is worse than a plain one, so refuse to write it.
  const overflow = await page.evaluate(() => ({
    x: document.body.scrollWidth - document.body.clientWidth,
    y: document.body.scrollHeight - document.body.clientHeight,
  }))
  if (overflow.x > 1 || overflow.y > 1) {
    failures.push(`${spec.slug} overflows by ${overflow.x}px wide, ${overflow.y}px tall.`)
    continue
  }

  const buffer = await page.screenshot({ type: "jpeg", quality: QUALITY })
  const name = `${spec.slug}-${cardHash(spec)}.jpg`
  await writeFile(join(OUT, name), buffer)
  manifest[spec.slug] = name
  written.add(name)
}

await browser.close()

// Drop superseded and orphaned cards, so the folder cannot silently grow.
for (const name of await readdir(OUT)) {
  if (name.endsWith(".jpg") && !written.has(name)) {
    await unlink(join(OUT, name))
    console.log(`  removed stale ${name}`)
  }
}

await writeFile(MANIFEST, `${JSON.stringify(manifest, null, 2)}\n`)

// The card filenames change on every edit, so nothing may hardcode one. The
// app reads them from here, and index.html — which is what a crawler sees
// before any JavaScript runs — is rewritten in place.
const DATA = new URL("../src/data/og-cards.ts", import.meta.url).pathname
await writeFile(
  DATA,
  [
    "// Generated by scripts/og-cards.mjs. Do not edit.",
    "// Card filenames carry a content hash so an edited card is a new URL:",
    "// social platforms cache what they derive from an image URL and never",
    "// re-derive it when the bytes behind that URL change.",
    "export const ogCards = {",
    ...Object.entries(manifest).map(([slug, file]) => `  ${JSON.stringify(slug)}: ${JSON.stringify(file)},`),
    "} as const",
    "",
    "export type OgCardSlug = keyof typeof ogCards",
    "",
    "export function ogCardUrl(siteUrl: string, slug: OgCardSlug): string {",
    `  return \`\${siteUrl}/${CARD_DIR}/\${ogCards[slug]}\``,
    "}",
    "",
  ].join("\n")
)

const INDEX = new URL("../index.html", import.meta.url).pathname
const home = `https://kousikdutta.com/${CARD_DIR}/${manifest.home}`
const before = await readFile(INDEX, "utf8")
const after = before.replace(
  /(<meta (?:property="og:image"|name="twitter:image") content=")[^"]*(")/gu,
  `$1${home}$2`
)
if (after !== before) {
  await writeFile(INDEX, after)
  console.log("  updated index.html to the new home card")
}

if (failures.length > 0) {
  console.error(`\nog-cards failed:\n${failures.map((line) => `  ${line}`).join("\n")}`)
  process.exit(1)
}

console.log(`Wrote ${written.size} social cards to public/assets/og/.`)
