// Generated by scripts/build-report.mjs on every build. Do not edit by hand.
// Editing this file is pointless: the next build overwrites it.

export type BuildGate = {
  id: string
  label: string
  summary: string
  metric: string
}

export type BuildReport = {
  generatedAt: string
  chain: string[]
  gates: BuildGate[]
  assets: { imageCount: number; imageMb: number; formats: Record<string, number> }
  journalCount: number
}

export const BUILD_REPORT: BuildReport = {
  "generatedAt": "2026-08-02",
  "chain": [
    "tsc -b",
    "build-report",
    "vite build",
    "postbuild",
    "check-glass",
    "check-a11y",
    "check-weight"
  ],
  "gates": [
    {
      "id": "check-glass",
      "label": "Glass surfaces",
      "summary": "Confirms every layered-glass rule survived the CSS build, so the depth treatment cannot be silently dropped by a refactor or an over-eager purge.",
      "metric": "5 rules verified"
    },
    {
      "id": "check-a11y",
      "label": "Colour and target size",
      "summary": "Recomputes contrast for every colour token pair in both themes against WCAG AA, and requires interactive text controls to be at least 24px tall. It caught four real contrast defects when it was introduced.",
      "metric": "37 checks"
    },
    {
      "id": "check-weight",
      "label": "Asset weight",
      "summary": "Fails on any image over 400KB, any unconverted raster, and any source model left where it would be deployed. Added after the homepage was found shipping 8MB.",
      "metric": "11.0MB of 15MB budget"
    }
  ],
  "assets": {
    "imageCount": 165,
    "imageMb": 11,
    "formats": {
      "webp": 162,
      "jpg": 1,
      "svg": 1,
      "png": 1
    }
  },
  "journalCount": 25
}
